### ISSUE TITLE
Madmom build issues

### ISSUE THREAD

**Issue by Ashoat** [campmindshark/spectrum#34]
I've asked three different people to follow the instructions in this repo's `README` to install Spectrum, and each of them have had issues getting Madmom to build properly. There is something wrong with the [`Madmom.pyproj` file](https://github.com/campmindshark/madmom/blob/master/Madmom.pyproj) that configures the build process. We should get this figured out and fixed ahead of the next burn

**Comment by brendan-rice** [comment]
I had issues with it. I had to manually install the Python packages using [visual studio](https://www.screencast.com/t/h5D8tiIsJ).

The packages that were missing were:

Cython
madmon
numpy

Once these were installed the pulled in whatever other package dependencies and the solution built.

**Comment by larryfenn** [comment]
I also had issues, but I traced it to the `pip` being the wrong version - after a long process of troubleshooting I uninstalled all Python versions, installed 3.7, and pointed my system path variable to the correct `pip` version (it had `~\AppData\Local\Programs\Python39` but it should have been `~\AppData\Local\Programs\Python37`) it built correctly.

I think this is something to do with the virtualenv not being activated in the build steps, so it's just using your system Python settings.

**Comment by Ashoat** [comment]
Unfortunately still an issue

**Comment by Ashoat** [comment]
Okay I think things 100% work now with 0691928c86429d3080140900ee2d180f383a20ed (along with the other recent fixes)
